### ISSUE TITLE
Text alignment with formula image

### ISSUE THREAD

**Issue by vimaxwell** [uetchy/math-api#33]
When I write a passage with formula like this https://codepen.io/vimaxwell/pen/qBErPqE, the multiple-line formula works correctly but I have a problem with the single-line formula that stays below the text.
![image](https://user-images.githubusercontent.com/19898639/71229460-2844b480-2318-11ea-820b-a7c808395e45.png).
I tried to change the attribute `vertical-align` but it doesn't work.

Can you suggest me how to fix it to render like this?
![image](https://user-images.githubusercontent.com/19898639/71229482-46121980-2318-11ea-83e4-c10f17532a5b.png)

**Comment by uetchy** [comment]
Use `vertical-align: baseline;`.

https://codepen.io/uetchy/pen/wvBJrmj

Also change `math.now.sh?from=` to `math.now.sh?inline=` for inline notation.

**Comment by cben** [comment]
`vertical-align: baseline;` only looks OK for small formulas, or formulas that only ascend above the text.  (`inline` helps keep them a it smaller)  
But when formula descends significantly down, it will look out of place.

If you want to align formulas "blindly" without thinking what kind of formula it is, a quick-and-dirty approach that might help is padding the formula vertically so that it's balanced and can always use `vertical-align: middle;`.  
An easy way to achieve balancing is wrapping with paired delimiters.  See https://tex.stackexchange.com/a/722922/7262 and https://www.overleaf.com/read/tmhcwxwdntnh#f8a862 for more details, but this particular converter actually works better in some ways so can do it "right":
```
\vphantom{\left| 1+\cfrac{1+\cfrac{y}{z}}{x} \right|}
1+\cfrac{1+\cfrac{y}{z}}{x}
```

Approx Demo: (using `<img align="middle">`, as of 2024-07 GitHub's sanitizer seems to pass that attr though, but CSS `vertical-align: middle;` would align better):

> -----
>
> prev line  
> Text-- <img src="https://math.vercel.app/?bgcolor=yellow&from=%5Cvphantom%7B%5Cleft%5B%201%2B%5Ccfrac%7B1%2B%5Ccfrac%7By%7D%7Bz%7D%7D%7Bx%7D%20%5Cright%5D%7D%0A1%2B%5Ccfrac%7B1%2B%5Ccfrac%7By%7D%7Bz%7D%7D%7Bx%7D.svg" align="middle"> -text- <img src="https://math.vercel.app/?bgcolor=yellow&from=%5Cvphantom%7B%5Cleft%5B%20e%20%3D%202%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%201%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%202%20%2B%20%5Ccfrac%7B2%7D%7B%0A%20%203%20%2B%20%5Ccfrac%7B3%7D%7B%0A%20%204%20%2B%20%5Ccfrac%7B4%7D%7B%5Cldots%7D%0A%7D%7D%7D%7D%20%5Cright%5D%7D%0Ae%20%3D%202%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%201%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%202%20%2B%20%5Ccfrac%7B2%7D%7B%0A%20%203%20%2B%20%5Ccfrac%7B3%7D%7B%0A%20%204%20%2B%20%5Ccfrac%7B4%7D%7B%5Cldots%7D%0A%7D%7D%7D%7D.svg" align="middle"> --text.  
> next line
>
> -----
